namespace Contractor.Core.Generation
{
    public enum ClassGenerationTag
    {
        BACKEND,
        BACKEND_MISC,
        BACKEND_API,
        BACKEND_CONTRACT,
        BACKEND_CONTRACT_LOGIC,
        BACKEND_CONTRACT_PERSISTENCE,
        BACKEND_LOGIC,
        BACKEND_LOGIC_TESTS,
        BACKEND_PERSISTENCE,
        BACKEND_PERSISTENCE_REPOSITORY,
        BACKEND_PERSISTENCE_DB_CONTEXT,
        BACKEND_GENERATED,
        BACKEND_GENERATED_DTOS,
        BACKEND_GENERATED_PERSISTENCE,
        FRONTEND,
        FRONTEND_MODEL,
        FRONTEND_PAGES
    }
}