name: .NET

on:
  push:
    tags: 
     - 1.*

jobs:
  build:
    name: 'Build Contractor'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile
    - name: Rename Artifact
      run: mv Contractor.CLI/bin/Release/netcoreapp3.1/publish/Contractor.CLI.exe Contractor.CLI/bin/Release/netcoreapp3.1/publish/contractor.exe
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: contractor
        path: ./Contractor.CLI/bin/Release/netcoreapp3.1/publish/contractor.exe
        
  release:
    name: 'Create GitHub Release for Contractor'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:      
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: contractor
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./Contractor.CLI/bin/Release/netcoreapp3.1/publish/contractor.exe
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}

